image: sikalabs/ci

stages:
  - static_analysis
  - build
  - deploy_dev

variables:
  IMAGE_BACKEND_LATEST: $CI_REGISTRY_IMAGE/backend
  IMAGE_BACKEND: $CI_REGISTRY_IMAGE/backend:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA-$CI_PIPELINE_ID
  IMAGE_FRONTEND_LATEST: $CI_REGISTRY_IMAGE/frontend
  IMAGE_FRONTEND: $CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA-$CI_PIPELINE_ID
  HOST_FRONTEND: $CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG.$KUBE_INGRESS_BASE_DOMAIN
  GIT_CLEAN_FLAGS: -ffdx -e node_modules -e .yarn-cache

.frontend_static_analysis: &frontend_static_analysis
  stage: static_analysis
  image: node:17
  script:
    - cd frontend
    - yarn --cache-folder .yarn-cache
    - yarn --cache-folder .yarn-cache run $CMD

frontend:prettier:
  <<: *frontend_static_analysis
  variables:
    CMD: prettier-write


frontend:lint:
  <<: *frontend_static_analysis
  variables:
    CMD: lint

build:frontend:
  stage: build
  script:
    - cd frontend
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker build -t $IMAGE_FRONTEND -t $IMAGE_FRONTEND_LATEST .
    - docker push $IMAGE_FRONTEND
    - docker push $IMAGE_FRONTEND_LATEST
  needs:
    - frontend:prettier
    - frontend:lint

build:backend:
  stage: build
  script:
    - cd backend
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker build -t $IMAGE_BACKEND -t $IMAGE_BACKEND_LATEST .
    - docker push $IMAGE_BACKEND
    - docker push $IMAGE_BACKEND_LATEST
  needs: []

deploy_dev:frontend:
  stage: deploy_dev
  script:
    - helm upgrade --install
        frontend-$CI_COMMIT_REF_SLUG one-image
        --wait
        --repo https://helm.sikalabs.io
        --set image=$IMAGE_FRONTEND
        --set host=$HOST_FRONTEND
        --set CI_PROJECT_PATH_SLUG=$CI_PROJECT_PATH_SLUG
        --set CI_ENVIRONMENT_SLUG=$CI_ENVIRONMENT_SLUG
  environment:
    name: dev/frontend/$CI_COMMIT_REF_SLUG
    url: https://$CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG.$KUBE_INGRESS_BASE_DOMAIN
    kubernetes:
      namespace: default
    on_stop: stop_dev:frontend
  needs:
    - build:frontend

stop_dev:frontend:
  when: manual
  stage: deploy_dev
  variables:
    GIT_STRATEGY: none
  allow_failure: false
  script:
    - helm uninstall frontend-$CI_COMMIT_REF_SLUG
  environment:
    name: dev/frontend/$CI_COMMIT_REF_SLUG
    kubernetes:
      namespace: default
    action: stop
