image: sikalabs/ci

stages:
  - build

variables:
  IMAGE_FRONTEND: $CI_REGISTRY_IMAGE/frontend

build:frontend:
  stage: build
  script:
    - cd frontend
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker build -t $IMAGE_FRONTEND .
    - docker push $IMAGE_FRONTEND
