image: sikalabs/ci

stages:
  - build
  - deploy_dev

variables:
  IMAGE_FRONTEND: $CI_REGISTRY_IMAGE/frontend
  HOST_FRONTEND: $CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG.$KUBE_INGRESS_BASE_DOMAIN

build:frontend:
  stage: build
  script:
    - cd frontend
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker build -t $IMAGE_FRONTEND .
    - docker push $IMAGE_FRONTEND

deploy_dev:frontend:
  stage: deploy_dev
  script:
    - helm upgrade --install
        frontend one-image
        --wait
        --repo https://helm.sikalabs.io
        --set image=$IMAGE_FRONTEND
        --set host=$HOST_FRONTEND
        --set CI_PROJECT_PATH_SLUG=$CI_PROJECT_PATH_SLUG
        --set CI_ENVIRONMENT_SLUG=$CI_ENVIRONMENT_SLUG
  environment:
    name: dev/frontend/$CI_COMMIT_REF_SLUG
    url: https://$CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG.$KUBE_INGRESS_BASE_DOMAIN
    kubernetes:
      namespace: default
    on_stop: stop_dev:frontend

stop_dev:frontend:
  when: manual
  stage: deploy_dev
  script:
    - helm uninstall frontend
  environment:
    name: dev/frontend/$CI_COMMIT_REF_SLUG
    kubernetes:
      namespace: default
    action: stop
